title: mglnk shortener 
description: mglnk Link Shortener 
logo: /assets/img/M-and-G_colored-rotated.png
show_downloads: true
google_analytics:
theme: athene

permalink: /:slug/

plugins:
  - jekyll-redirect-from

repository: hlaueriksson/jekyll-url-shortener
